set_schedule_attributes:
  description: Sets custom attributes on a schedule entity for the Smarter Heat Pump.
  fields:
    entity_id:
      description: The schedule entity to update.
      example: schedule.heat_pump_schedule
    data:
      description: A dictionary of attributes to set on the schedule entity.
      example: '{"target_temperature": 22, "run_if": "{{ is_state('binary_sensor.workday', 'on') }}"}'
